language: python

python:
        - '3.8'
install:
        - make dev_env

env:
        global:
                -PYTHONPATH=/home/travis/build/csongbird/Pitch-n

script:
        - make tests  
        
after_success:
        - pip install coveralls
        - coveralls

deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: sd-pitch-n
        skip_cleanup: true
        on:
                all_branches: true
